services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    networks:
      - internal

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - internal

  mysql-user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banksphere_user
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '33061:3306'
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 5s
      retries: 5
    networks:
      - internal

  mysql-account:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banksphere_account
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '33062:3306'
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 5s
      retries: 5
    networks:
      - internal

  mysql-transaction:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banksphere_transaction
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '33063:3306'
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 5s
      retries: 5
    networks:
      - internal

  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    ports:
      - '8080:8080'
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - internal

  user-service:
    build: ./user
    image: user-service:latest
    expose:
      - '8081'
    depends_on:
      - mysql-user
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/banksphere_user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - internal

  account-service:
    build: ./account
    image: account-service:latest
    expose:
      - '8082'
    depends_on:
      - mysql-account
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-account:3306/banksphere_account
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=account-service
    networks:
      - internal

  transaction-service:
    build: ./transaction
    image: transaction-service:latest
    expose:
      - '8083'
    depends_on:
      - mysql-transaction
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-transaction:3306/banksphere_transaction
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
networks:
  internal:
    driver: bridge
