
##########################################################################
# WE NEED TO RE-EVALUATE AND TEST THIS CONFIGURATION FILE FOR ANY CHANGES

# 1. routes for microservices: uri, predicate, filter
# 2. security: oauth2 and jwt server if there is any URL --> we have JWT in doFilter and we dont need OAuth2 server, it is open to discussion
# 3. server and logging modes: DEBUG, INFO
# 4. additional configuration if needed
##########################################################################

spring:
  cloud:
    gateway:
      routes:
        # API Gateway route for the User microservice
        # Requests matching /users/** will be forwarded to http://localhost:8081
        - id: user-service
          uri: http://localhost:8081  # Destination User service URL
          predicates:
            - Path=/users/**  # Only routes requests that start with /users/
          filters:
            - StripPrefix=1  # Removes /users/ from the request before forwarding

        # API Gateway route for the Account microservice
        # Requests matching /accounts/** will be forwarded to http://localhost:8082
        - id: account-service
          uri: http://localhost:8082  # Destination Account service URL
          predicates:
            - Path=/accounts/**  # Only routes requests that start with /accounts/
          filters:
            - StripPrefix=1  # Removes /accounts/ from the request before forwarding

        # API Gateway route for the Transaction microservice
        # Requests matching /transactions/** will be forwarded to http://localhost:8083
        - id: transaction-service
          uri: http://localhost:8083  # Destination Transaction service URL
          predicates:
            - Path=/transactions/**  # Only routes requests that start with /transactions/
          filters:
            - StripPrefix=1  # Removes /transactions/ from the request before forwarding

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-auth-server.com  # OAuth2 Authorization Server URL for JWT validation

# Server settings
server:
  port: 8080  # API Gateway runs on port 8080

# Logging configuration
logging:
  level:
    com.example: DEBUG  # Set logging level for com.example package